_BASE_: [
  '../datasets/coco_instance.yml',
  '../runtime.yml',
  '_base_/solov2_r50_fpn.yml',
  '_base_/optimizer_1x.yml',
  '_base_/solov2_reader.yml',
]
weights: /home/kb/MyProjects/MultiModalInstanceSeg/PaddleDetection/pretrained_models/solov2/solov2_r50_fpn_1x_coco.pdparams # output/solov2_r50_fpn_1x_coco/model_final
